name: Run Stock Scanner

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: 라이브러리 설치
        run: |
          pip install -r requirements.txt

      - name: Python 실행
        run: |
          python main.py
        env:
          KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}
          KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}
